title: Emma Sewell # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with skills in Python and SQL. First class Masters in Physics with Astrophysics.
  <br><br>
  Currently employed.
  <br><br>
  <a href="https://www.linkedin.com/in/emma-sewell-57a10715b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
